### ISSUE TITLE
Dataset Preprocessing 

### ISSUE THREAD

**Issue by suhani221** [USC-InfoLab/NeuroGNN#1]
hi i was trying to run the original author work using the kaggle dataset but while pre-processing some 800 files failed for me , does it happen with you too?

**Comment by suhani221** [comment]
@Arashhs

**Comment by Arashhs** [comment]
Hi @suhani221,

We did not face any issues running the [baseline](https://github.com/tsy935/eeg-gnn-ssl)'s preprocessing code on the Kaggle dataset. What error do you get?

**Comment by Arashhs** [comment]
Closing the issue since the preprocessing step works fine on our machines and we did not hear any updates from @suhani221.
