### ISSUE TITLE
Where is the data in kaggle?

### ISSUE THREAD

**Issue by kroesufos** [USC-InfoLab/NeuroGNN#2]
https://www.kaggle.com/datasets/psyryuvok/the-tuh-eeg-seizure-corpus-tusz-v152 doesnt work anymore, is there any alternative?

**Comment by Arashhs** [comment]
As per the updated data provider's guidelines, you need to apply to access the dataset through their official website: https://isip.piconepress.com/projects/nedc/html/tuh_eeg/

I updated the README accordingly.
